version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_versions: [">=1.0.0"]
    versioning:
      file:
        - name: requirements.txt
        - name: setup.py
